// LISTAGEM DE PUBLICAÇÕES
export const CHANGE_CATEGORY = "CHANGE_CATEGORY";
export const CHANGE_SORT = "CHANGE_SORT";
export const LIST_CATEGORIES = "LIST_CATEGORIES";
export const LIST_POSTS = "LIST_POSTS";
export const UPDATE_POSTS = "UPDATE_POSTS";
export const EDIT_POST = "EDIT_POST";
export const SHOW_POST = "SHOW_POST";
export const DIALOG_POST_FORM = "DIALOG_POST_FORM";

// COMENTÁRIOS
export const DETAIL_OPEN_DIALOG_COMMENT = "DETAIL_OPEN_DIALOG_COMMENT";
export const DETAIL_POST_HANDLE_CHANGE = "DETAIL_POST_HANDLE_CHANGE";
export const DETAIL_GET_ALL_COMMENTS = "DETAIL_GET_ALL_COMMENTS";
export const DETAIL_GET_COMMENT = "DETAIL_GET_COMMENT";
export const DETAIL_ADD_COMMENT = "DETAIL_ADD_COMMENT";
export const DETAIL_EDIT_COMMENT = "DETAIL_EDIT_COMMENT";
export const DETAIL_REMOVE_COMMENT = "DETAIL_REMOVE_COMMENT";
export const DETAIL_VOTE_COMMENT = "DETAIL_REMOVE_COMMENT";
export const DETAIL_COMMENT_FORM_CLEAN = "DETAIL_COMMENT_FORM_CLEAN";
export const DETAIL_COMMENT_VOTE = "DETAIL_COMMENT_VOTE";

// FORM ULÁRIO DE EDIÇÃO DA PUBLICAÇÃO
export const POST_HANDLE_CHANGE = "POST_HANDLE_CHANGE";
export const POST_CHANGE_CATEGORY = "POST_CHANGE_CATEGORY";
export const POST_FORM_SAVE = "POST_FORM_SAVE";
export const POST_VALID_FORM = "POST_VALID_FORM";
export const POST_CLEAN_FORM = "POST_CLEAN_FORM";
export const POST_LOAD_DATA = "POST_LOAD_DATA";
export const POST_REMOVE = "POST_REMOVE";
export const POST_VOTE = "POST_VOTE";
export const DETAIL_GET_POST = "DETAIL_GET_POST";